name: pyt
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pillow
  - pytest
  - python=3.9
  - pytorch=1.11
  - scipy
  - torchaudio
  - torchvision
  - tqdm
  - pip
  - pip:
    - easydict
    - einops
    - gitpython
    - h5py
    - jupyterlab-vim
    - jupyterlab-vimrc
    - omegaconf
    - opencv-python
    - pyyaml
    - scikit-learn
    - scikit-image
    - tensorboard
    - wget
