#!/usr/bin/env python

from pathlib import Path
import shutil

import tyro

from flow_utils import SRC_ROOT

def mkdir_overwrite_or_abort(root_path, yes=False):
    """
    root_path should be a pathlib.Path
    """
    if root_path.exists():
        # Overwrite?
        if yes:
            shutil.rmtree(root_path)
        else:
            yn = input(
                f'{root_path} exists. Overwrite? [y/n] '
            ).lower()
            if yn == 'y':
                shutil.rmtree(root_path)
            else:
                print('Aborting.')
                sys.exit()
    Path(root_path).mkdir(parents=True, exist_ok=True)



def main(
        name: str,
        copy_from: Path = Path(__file__).parent/'.template_exp',
):
    # Copy over stuff
    shutil.copytree(
        src=copy_from,
        dst=str(SRC_ROOT/name),
    )
    print(f'Copied experiment from {copy_from} to '\
          + f'{str(SRC_ROOT/name)}')

if __name__ == '__main__':
    tyro.cli(main)
